import type { Metadata } from "next";
import "./styles/nprogress-custom.css";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import { camptonFont } from "@/components/auth/header";
import NProgressWrapper from "@/NprogressWrapper";
import { Suspense } from "react"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${camptonFont.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={null}>
            <NProgressWrapper>
              {children}
              <Toaster richColors position="top-right" />
            </NProgressWrapper>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}