export const usersData = [
    {
      id: "0001",
      name: "Daniel Aderi C.",
      email: "danieladeri@yahoo.com",
      profileType: "Musician",
      status: "Active",
      verified: true,
      lastLogin: "19/04/25 • 9:00 AM",
      image: "https://via.placeholder.com/150/0001",
    },
    {
      id: "0002",
      name: "Michael Ajob E.",
      email: "michaelajob@gmail.com",
      profileType: "Professional Studio",
      status: "Active",
      verified: true,
      lastLogin: "12/04/25 • 2:45 AM",
      image: "https://via.placeholder.com/150/0002",
    },
    {
      id: "0004",
      name: "James D. Shola",
      email: "jamesshola@gmail.com",
      profileType: "Talent Agency",
      status: "Suspended",
      verified: true,
      lastLogin: "19/04/25 • 10:14 PM",
      image: "https://via.placeholder.com/150/0004",
    },
    {
      id: "0005",
      name: "Anit Adeboyo",
      email: "adeboyoanit@gmail.com",
      profileType: "Music Business Coa...",
      status: "Active",
      verified: true,
      lastLogin: "20/04/25 • 10:00 AM",
      image: "https://via.placeholder.com/150/0005",
    },
    {
      id: "0006",
      name: "Amakiri Justina",
      email: "amakirijustina@gmail.com",
      profileType: "Producer",
      status: "Deactivated",
      verified: true,
      lastLogin: "01/03/25 • 1:00 AM",
      image: "https://via.placeholder.com/150/0006",
    },
  ];
  
  export const bookingsData = [
    {
      id: "B001",
      user: "Daniel Aderi C.",
      event: "Concert",
      date: "19/04/25",
      status: "Confirmed",
      amount: "$500",
    },
    {
      id: "B002",
      user: "Michael Ajob E.",
      event: "Studio Session",
      date: "12/04/25",
      status: "Pending",
      amount: "$300",
    },
    {
      id: "B003",
      user: "James D. Shola",
      event: "Talent Showcase",
      date: "19/04/25",
      status: "Cancelled",
      amount: "$200",
    },
  ];
  
  export const transactionsData = [
    {
      id: "T001",
      user: "Daniel Aderi C.",
      bookingId: "B001",
      date: "19/04/25",
      status: "Completed",
      amount: "$500",
    },
    {
      id: "T002",
      user: "Michael Ajob E.",
      bookingId: "B002",
      date: "12/04/25",
      status: "Pending",
      amount: "$300",
    },
    {
      id: "T003",
      user: "James D. Shola",
      bookingId: "B003",
      date: "19/04/25",
      status: "Failed",
      amount: "$200",
    },
  ];