export const usersData = [
  {
    id: "0001",
    name: "Daniel Aderi C.",
    email: "danieladeri@yahoo.com",
    profileType: "Musician",
    status: "Active",
    verified: true,
    lastLogin: "19/04/25 • 9:00 AM",
    image: "https://via.placeholder.com/150/0001",
  },
  {
    id: "0002",
    name: "Michael Ajob E.",
    email: "michaelajob@gmail.com",
    profileType: "Professional Studio",
    status: "Active",
    verified: true,
    lastLogin: "12/04/25 • 2:45 AM",
    image: "https://via.placeholder.com/150/0002",
  },
  {
    id: "0004",
    name: "James D. Shola",
    email: "jamesshola@gmail.com",
    profileType: "Talent Agency",
    status: "Suspended",
    verified: true,
    lastLogin: "19/04/25 • 10:14 PM",
    image: "https://via.placeholder.com/150/0004",
  },
  {
    id: "0005",
    name: "Anit Adeboyo",
    email: "adeboyoanit@gmail.com",
    profileType: "Music Business Coa...",
    status: "Active",
    verified: true,
    lastLogin: "20/04/25 • 10:00 AM",
    image: "https://via.placeholder.com/150/0005",
  },
  {
    id: "0006",
    name: "Amakiri Justina",
    email: "amakirijustina@gmail.com",
    profileType: "Producer",
    status: "Deactivated",
    verified: true,
    lastLogin: "01/03/25 • 1:00 AM",
    image: "https://via.placeholder.com/150/0006",
  },
];

export const bookingsData = [
  {
    id: "BK-001",
    clientName: "Daniel Aderi C.",
    clientEmail: "danieladeri@gmail.com",
    providerName: "Music Minds Studio",
    providerEmail: "musicminds@gmail.com",
    serviceOffered: "Concert",
    scheduledDate: "Apr 19, 2025",
    scheduledTime: "09:00 - 10:00 AM",
    location: "Los Angeles, CA, US",
    totalAmount: "$500",
    paymentAmount: "$450",
    platformFee: "$50",
    transactionId: "Trx001_ABC",
    status: "Confirmed",
    lastLogin: "Apr 19, 2025 • 09:00 AM",
  },
  {
    id: "BK-002",
    clientName: "Michael Ajob E.",
    clientEmail: "michaelajob@gmail.com",
    providerName: "SoundWave Productions",
    providerEmail: "soundwave@gmail.com",
    serviceOffered: "Studio Session",
    scheduledDate: "Apr 12, 2025",
    scheduledTime: "02:30 - 04:30 PM",
    location: "New York, NY, US",
    totalAmount: "$300",
    paymentAmount: "$250",
    platformFee: "$50",
    transactionId: "Trx002_XYZ",
    status: "Pending",
    lastLogin: "Apr 12, 2025 • 02:30 PM",
  },
  {
    id: "BK-003",
    clientName: "James D. Shola",
    clientEmail: "jamesdshola@gmail.com",
    providerName: "Talent Agency Inc.",
    providerEmail: "talentagency@gmail.com",
    serviceOffered: "Talent Showcase",
    scheduledDate: "Apr 19, 2025",
    scheduledTime: "11:15 AM - 12:15 PM",
    location: "Chicago, IL, US",
    totalAmount: "$200",
    paymentAmount: "$150",
    platformFee: "$50",
    transactionId: "Trx003_PQR",
    status: "Cancelled",
    lastLogin: "Apr 19, 2025 • 11:15 AM",
  },
  {
    id: "BK-004",
    clientName: "Daniel Aderi C.",
    clientEmail: "danieladeri@gmail.com",
    providerName: "Michael Ajobi Emmanuel",
    providerEmail: "michaelajobi@gmail.com",
    serviceOffered: "Vocal Coaching",
    scheduledDate: "Apr 16, 2025",
    scheduledTime: "09:00 - 10:00 AM",
    location: "Honolulu, Hawaii, US",
    totalAmount: "$170",
    paymentAmount: "$120",
    platformFee: "$50",
    transactionId: "Trx032_dS8",
    status: "Processed",
    lastLogin: "Apr 16, 2025 • 09:00 AM",
  },
];

export const transactionsData = [
  {
    id: "T001",
    clientName: "Daniel Aderi C.",
    bookingId: "B001",
    providerName: "Music Minds Studio",
    serviceOffered: "Concert",
    totalAmount: "$500",
    status: "Completed",
    lastLogin: "19/04/25 • 9:00 AM",
    image: "https://via.placeholder.com/150/0001",
  },
  {
    id: "T002",
    clientName: "Michael Ajob E.",
    bookingId: "B002",
    providerName: "SoundWave Productions",
    serviceOffered: "Studio Session",
    totalAmount: "$300",
    status: "Pending",
    lastLogin: "12/04/25 • 2:30 PM",
    image: "https://via.placeholder.com/150/0001",
  },
  {
    id: "T003",
    clientName: "James D. Shola",
    bookingId: "B003",
    providerName: "Talent Agency Inc.",
    serviceOffered: "Talent Showcase",
    totalAmount: "$200",
    status: "Failed",
    lastLogin: "19/04/25 • 11:15 AM",
    image: "https://via.placeholder.com/150/0001",
  },
];

export const supportData = [
  {
    id: "AN-001",
    user: "Daniel Aderi C.",
    issue: "Login issue",
    priority: "High",
    status: "In progress",
    createdDate: "19/04/25 • 9:00 AM",
  },
  {
    id: "AN-002",
    user: "Michael Ajob E.",
    issue: "Payment failed",
    priority: "Medium",
    status: "Resolved",
    createdDate: "19/04/25 • 9:00 AM",
  },
  {
    id: "AN-003",
    user: "James D. Shola",
    issue: "Failed OTP",
    priority: "Low",
    status: "Open",
    createdDate: "19/04/25 • 9:00 AM"
  }
]

export const adminData = [
  {
    name: "Daniel Aderi C.",
    email: "danieladeri@yahoo.com",
    role: "Admin",
    dateAdded: "Pending",
    lastLogin: "",
  },

]

export const notificationsData = [
  {
    id: "NOT-001",
    type: "system",
    message: "System detected unusual login activity from John Smith",
    timestamp: "Apr 16, 2025 • 9:10 AM",
    read: false,
    actions: [{ label: "Investigate", variant: "default" as const }],
  },
  {
    id: "NOT-002",
    type: "booking",
    message: "New booking request (BK-004) from Daniel Lee for 'Anna Lee' - $50, pending approval",
    timestamp: "Apr 16, 2025 • 10:45 AM",
    read: false,
    actions: [
      { label: "Approve", variant: "default" as const },
      { label: "Cancel", variant: "outline" as const },
    ],
  },
  {
    id: "NOT-003",
    type: "user",
    message: "New user 'Maria Gonzalez' registered as a Musician. Profile pending verification.",
    timestamp: "Apr 16, 2025 • 11:05 AM",
    read: false,
    actions: [{ label: "Verify Profile", variant: "default" as const }],
  },
  {
    id: "NOT-004",
    type: "support",
    message: "Reminder: 3 support tickets (T-#45) remain unresolved.",
    timestamp: "Apr 20, 2025 • 01:45 PM",
    read: true,
    actions: [{ label: "Take Action", variant: "default" as const }],
  },
  {
    id: "NOT-005",
    type: "security",
    message: "Potential security breach attempt detected on user Maria Gonzalez' account.",
    timestamp: "Apr 20, 2025 • 9:10 AM",
    read: false,
    actions: [{ label: "Lock Account", variant: "default" as const }],
  },
  {
    id: "NOT-006",
    type: "security",
    message: "Potential security breach attempt detected on user Maria Gonzalez' account.",
    timestamp: "Apr 20, 2025 • 9:10 AM",
    read: false,
    actions: [{ label: "Lock Account", variant: "default" as const }],
  },
];


export const kycData = [
  {
    id: "USR-001",
    name: "Daniel Adaeri C.",
    email: "danieladaeri@yahoo.com",
    kycStatus: "Approved",
    submittedDate: "Apr 25, 2025",
    role: "Musician",
    studioName: "XYZ Media Solutions, Inc.",
    website: "www.xyzmediasolutions.com",
    phone: "+1 44483992075",
    address: "123 Main Street",
    city: "CA 1223",
    province: "Canada",
  },
  {
    id: "USR-002",
    name: "Michael Ajobi E.",
    email: "michaelajobi@gmail.com",
    kycStatus: "Submitted",
    submittedDate: "Apr 25, 2025",
    role: "Producer",
    studioName: "SoundWave Studios",
    website: "www.soundwavestudios.com",
    phone: "+1 5551234567",
    address: "456 Oak Avenue",
    city: "ON 5678",
    province: "Canada",
  },
  {
    id: "USR-003",
    name: "Francis Praise...",
    email: "francispraisegod@yahoo.com",
    kycStatus: "Declined",
    submittedDate: "Apr 25, 2025",
    role: "Engineer",
    studioName: "AudioTech Hub",
    website: "www.audiotechhub.com",
    phone: "+1 6667890123",
    address: "789 Pine Road",
    city: "BC 9012",
    province: "Canada",
  },
  {
    id: "USR-004",
    name: "James D. Shola",
    email: "jamesshola@gmail.com",
    kycStatus: "Approved",
    submittedDate: "Apr 25, 2025",
    role: "Musician",
    studioName: "Harmony Beats",
    website: "www.harmonybeats.com",
    phone: "+1 7773456789",
    address: "321 Cedar Lane",
    city: "QC 3456",
    province: "Canada",
  },
  {
    id: "USR-005",
    name: "Anitt Adebayo...",
    email: "adebayoanitt@gmail.com",
    kycStatus: "Approved",
    submittedDate: "Apr 25, 2025",
    role: "Producer",
    studioName: "Rhythm Factory",
    website: "www.rhythmfactory.com",
    phone: "+1 8889012345",
    address: "654 Birch Street",
    city: "ON 7890",
    province: "Canada",
  },
  {
    id: "USR-006",
    name: "Amakiri Justina...",
    email: "amakirijustina@gmail.com",
    kycStatus: "Submitted",
    submittedDate: "Apr 25, 2025",
    role: "Engineer",
    studioName: "Sonic Labs",
    website: "www.soniclabs.com",
    phone: "+1 9994567890",
    address: "987 Elm Drive",
    city: "BC 1234",
    province: "Canada",
  },
  {
    id: "USR-007",
    name: "Davida Nathan...",
    email: "davidakanse@gmail.com",
    kycStatus: "Declined",
    submittedDate: "Apr 25, 2025",
    role: "Musician",
    studioName: "BeatCrafters Inc.",
    website: "www.beatcrafters.com",
    phone: "+1 1112345678",
    address: "147 Maple Avenue",
    city: "QC 5678",
    province: "Canada",
  },
  {
    id: "USR-008",
    name: "Sarah Wilson",
    email: "sarahwilson@example.com",
    kycStatus: "Approved",
    submittedDate: "May 01, 2025",
    role: "Producer",
    studioName: "Echo Studios",
    website: "www.echostudios.com",
    phone: "+1 2223456789",
    address: "258 Oak Lane",
    city: "ON 9012",
    province: "Canada",
  },
  {
    id: "USR-009",
    name: "Michael Lee",
    email: "michaellee@example.com",
    kycStatus: "Submitted",
    submittedDate: "May 02, 2025",
    role: "Engineer",
    studioName: "Pulse Audio",
    website: "www.pulseaudio.com",
    phone: "+1 3334567890",
    address: "369 Pine Street",
    city: "BC 3456",
    province: "Canada",
  },
  {
    id: "USR-010",
    name: "Laura Adams",
    email: "lauraadams@example.com",
    kycStatus: "Declined",
    submittedDate: "May 03, 2025",
    role: "Musician",
    studioName: "Vibe Creators",
    website: "www.vibecreators.com",
    phone: "+1 4445678901",
    address: "470 Cedar Road",
    city: "QC 7890",
    province: "Canada",
  },
  {
    id: "USR-011",
    name: "Chris Evans",
    email: "chrisevans@example.com",
    kycStatus: "Approved",
    submittedDate: "May 04, 2025",
    role: "Producer",
    studioName: "SoundForge",
    website: "www.soundforge.com",
    phone: "+1 5556789012",
    address: "581 Birch Lane",
    city: "ON 1234",
    province: "Canada",
  },
];

export const reviewData = [
  {
    id: "RV-001",
    userName: "Michael Ajobi",
    email: "michaelajobi@gmail.com",
    serviceOffered: "Vocal Coaching",
    rating: 4.5,
    reviewText: "Excellent service! I loved it.",
    date: "Wed, Apr 16, 2025 09:00 AM",
    status: "Approved",
    flagged: "No",
    reviewer: {
      name: "Daniel Adaeri C.",
      email: "danieladaeri@yahoo.com",
      role: "Musician",
    },
  },
  {
    id: "RV-002",
    userName: "Michael Ajobi",
    email: "michaelajobi@gmail.com",
    serviceOffered: "Talent Agency",
    rating: 3.5,
    reviewText: "Great customer care and support.",
    date: "Wed, Apr 16, 2025 10:14 PM",
    status: "Approved",
    flagged: "No",
    reviewer: {
      name: "James D. Shola",
      email: "jamesdshola@gmail.com",
      role: "Talent Agency",
    },
  },
  {
    id: "RV-003",
    userName: "Davida Nathan",
    email: "davidanathan@yahoo.com",
    serviceOffered: "Music Business Coaching",
    rating: 3.5,
    reviewText: "I enjoyed working with them.",
    date: "Thu, Apr 17, 2025 01:00 PM",
    status: "Approved",
    flagged: "No",
    reviewer: {
      name: "Thank-God Ferd",
      email: "thankgodferd@outlook.com",
      role: "Music Business Coach",
    },
  },
  {
    id: "RV-004",
    userName: "Briana Radiel",
    email: "brianaradiel@gmail.com",
    serviceOffered: "Producing",
    rating: 2.5,
    reviewText: "Poor service, lack of professionalism.",
    date: "Sat, Jun 01, 2025 01:00 AM",
    status: "Rejected",
    flagged: "Yes",
    reviewer: {
      name: "Michael Ajobi Emmanuel",
      email: "michaelajobi@gmail.com",
      role: "Vocal Coach",
    },
  },
  {
    id: "RV-005",
    userName: "Thank-God Ferd",
    email: "thankgodferd@outlook.com",
    serviceOffered: "Vocal Coaching",
    rating: 4.5,
    reviewText: "Hands down excellent service.",
    date: "Mon, Apr 21, 2025 07:16 AM",
    status: "Approved",
    flagged: "No",
    reviewer: {
      name: "Amakiri Justina",
      email: "amakirijustina@gmail.com",
      role: "Vocal Coach",
    },
  },
  {
    id: "RV-006",
    userName: "Briana Radiel",
    email: "brianaradiel@gmail.com",
    serviceOffered: "Songwriting",
    rating: 4.3,
    reviewText: "Really loved the delivery and support.",
    date: "Mon, Mar 17, 2025 11:10 PM",
    status: "Approved",
    flagged: "Yes",
    reviewer: {
      name: "Davida Nathan",
      email: "davidanathan@yahoo.com",
      role: "Songwriter",
    },
  },
  {
    id: "RV-007",
    userName: "Amakiri Justina",
    email: "amakirijustina@gmail.com",
    serviceOffered: "Stage Management",
    rating: 3.5,
    reviewText: "Wonderful service & support.",
    date: "Mon, Apr 21, 2025 08:21 PM",
    status: "Approved",
    flagged: "No",
    reviewer: {
      name: "Briana Radiel",
      email: "brianaradiel@gmail.com",
      role: "Stage Manager",
    },
  },
];

export const announcementData = [
  {
    id: "ANN001",
    title: "New Feature Update",
    createdBy: "Daniel Adaeri C.",
    role: "Admin",
    status: "Published",
    publishedDate: "19/04/25 - 9:00 A.M.",
  },
  {
    id: "ANN002",
    title: "New Feature Update",
    createdBy: "Michael Ajobi E...",
    role: "Super Admin",
    status: "Published",
    publishedDate: "19/04/25 - 9:00 A.M.",
  },
  {
    id: "ANN003",
    title: "New Feature Update",
    createdBy: "Davida Nathan...",
    role: "Super Admin",
    status: "Draft",
    publishedDate: "19/04/25 - 9:00 A.M.",
  },
  {
    id: "ANN004",
    title: "New Feature Update",
    createdBy: "Briana Radiel Fr...",
    role: "Super Admin",
    status: "Archived",
    publishedDate: "19/04/25 - 9:00 A.M.",
  },
  {
    id: "ANN005",
    title: "New Feature Update",
    createdBy: "Thank-God Ferd...",
    role: "Super Admin",
    status: "Archived",
    publishedDate: "19/04/25 - 9:00 A.M.",
  },
  {
    id: "ANN006",
    title: "New Feature Update",
    createdBy: "Amakiri Justina...",
    role: "Super Admin",
    status: "Draft",
    publishedDate: "19/04/25 - 9:00 A.M.",
  },
];

export const supportTicketData = [
  {
    id: "AN-001",
    userName: "Daniel Adaeri C.",
    issue: "Payment Failed",
    priority: "High",
    status: "In progress",
    createdDate: "19/04/25 - 9:00 AM",
  },
  {
    id: "AN-002",
    userName: "Michael Ajobi E...",
    issue: "Failed Booking",
    priority: "Medium",
    status: "Resolved",
    createdDate: "19/04/25 - 9:00 AM",
  },
  {
    id: "AN-003",
    userName: "Davida Nathan...",
    issue: "Login Issue",
    priority: "Low",
    status: "Open",
    createdDate: "19/04/25 - 9:00 AM",
  },
  {
    id: "AN-004",
    userName: "Briana Radiel Fr...",
    issue: "Login Issue",
    priority: "Low",
    status: "In progress",
    createdDate: "19/04/25 - 9:00 AM",
  },
  {
    id: "AN-005",
    userName: "Thank-God Ferd...",
    issue: "Failed OTP",
    priority: "Medium",
    status: "Resolved",
    createdDate: "19/04/25 - 9:00 AM",
  },
  {
    id: "AN-006",
    userName: "Amakiri Justina...",
    issue: "Payment Failed",
    priority: "High",
    status: "Open",
    createdDate: "19/04/25 - 9:00 AM",
  },
  // Add more entries to reach 102 for pagination testing
  // ...Array.from({ length: 96 }, (_, i) => ({
  //   id: `AN-00${i + 7}`.slice(-6),
  //   userName: `User ${i + 7}...`,
  //   issue: `Issue ${i + 7}`,
  //   priority: ["High", "Medium", "Low"][Math.floor(Math.random() * 3)],
  //   status: ["In progress", "Resolved", "Open"][Math.floor(Math.random() * 3)],
  //   createdDate: "19/04/25 - 9:00 AM",
  // })),
];

export const broadcastMessageData = [
  {
    id: "BC-001",
    title: "Service Update",
    message: "New update underway...",
    createdBy: "Daniel Adaeri C.",
    recipientType: "All Users",
    status: "Sent",
    publishedDate: "19/04/25 - 9:00 AM",
    messageType: "Push Notification",
  },
  {
    id: "BC-002",
    title: "Service Update",
    message: "New update underway...",
    createdBy: "Michael Ajobi E...",
    recipientType: "Clients",
    status: "Scheduled",
    publishedDate: "19/04/25 - 9:00 AM",
    messageType: "Emergency Notification",
  },
  {
    id: "BC-003",
    title: "Promo Offer",
    message: "New update underway...",
    createdBy: "Davida Nathan...",
    recipientType: "Service Providers",
    status: "Draft",
    publishedDate: "N/A",
    messageType: "Push Notification",
  },
  {
    id: "BC-004",
    title: "Service Update",
    message: "New update underway...",
    createdBy: "Briana Radiel Fr...",
    recipientType: "All Users",
    status: "Sent",
    publishedDate: "19/04/25 - 9:00 AM",
    messageType: "Emergency Notification",
  },
  {
    id: "BC-005",
    title: "Promo Offer",
    message: "New update underway...",
    createdBy: "Thank-God Ferd...",
    recipientType: "All Users",
    status: "Sent",
    publishedDate: "19/04/25 - 9:00 AM",
    messageType: "Push Notification",
  },
  {
    id: "BC-006",
    title: "Service Update",
    message: "New update underway...",
    createdBy: "Amakiri Justina...",
    recipientType: "Client",
    status: "Draft",
    publishedDate: "N/A",
    messageType: "Emergency Notification",
  },
  // Add more entries to reach 102 for pagination testing
  // ...Array.from({ length: 96 }, (_, i) => ({
  //   id: `BC-00${i + 7}`.slice(-6),
  //   title: ["Service Update", "Promo Offer"][Math.floor(Math.random() * 2)],
  //   message: "New update underway...",
  //   createdBy: `User ${i + 7}...`,
  //   recipientType: ["All Users", "Clients", "Service Providers", "Client"][Math.floor(Math.random() * 4)],
  //   status: ["Sent", "Scheduled", "Draft"][Math.floor(Math.random() * 3)],
  //   publishedDate: Math.random() > 0.5 ? "19/04/25 - 9:00 AM" : "N/A",
  //   messageType: ["Push Notification", "Emergency Notification"][Math.floor(Math.random() * 2)],
  // })),
];

export const articleData = [
  { articleId: "AR-001", title: "How to Book a Vocal...", category: "Guides", status: "Published", publishedDate: "19/04/25 - 9:00 AM", createdBy: "Daniel Adaeri C." },
  { articleId: "AR-002", title: "How to Resolve Book...", category: "Troubleshooting", status: "Archived", publishedDate: "N/A", createdBy: "Michael Ajobi E..." },
  { articleId: "AR-003", title: "Navigating the Way...", category: "Guides", status: "Published", publishedDate: "19/04/25 - 9:00 AM", createdBy: "Davida Nathan..." },
  { articleId: "AR-004", title: "Understanding Tight...", category: "Policies", status: "Published", publishedDate: "19/04/25 - 9:00 AM", createdBy: "Briana Radiel Fr..." },
  { articleId: "AR-005", title: "Is it Free To Set-Up...", category: "FAQs", status: "Published", publishedDate: "19/04/25 - 9:00 AM", createdBy: "Thank-God Ferd..." },
  { articleId: "AR-006", title: "Validating Payments...", category: "News", status: "Draft", publishedDate: "N/A", createdBy: "Amakiri Justina..." },
  // Additional entries to reach 102 items
  // ...Array.from({ length: 96 }, (_, i) => ({
  //   articleId: `AR-00${i + 7}`.slice(-6),
  //   title: `Article Title ${i + 7}`,
  //   category: ["Guides", "Troubleshooting", "Policies", "FAQs", "News"][Math.floor(Math.random() * 5)],
  //   status: ["Published", "Archived", "Draft"][Math.floor(Math.random() * 3)],
  //   publishedDate: Math.random() > 0.3 ? "19/04/25 - 9:00 AM" : "N/A",
  //   createdBy: `Author ${i + 7}...`,
  // })),
];
